# https://ci.appveyor.com/project/jnsebgosselin/qwatson

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

branches:
  only:
    - master

skip_commits:
  files:
    - docs/*
    - '**/*.html'
    - '**/*.md'
    - '**/*.png'
    - '**/*.svg'
    - '**/*.jpg'

environment:
  matrix:
    - PYTHON_VERSION: "3.6"

platform:
  -x64

skip_branch_with_pr: true

install:
  # Cancel older builds for the same PR.
  # Credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - cmd: set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

  # Setup QWatson dev requirements.
  - python -m pip install -r requirements-dev.txt

  # Setup requirements for packaging QWatson.
  - python -m pip install pyinstaller
  - python -m pip install pywin32
  - python -m pip install tornado

build: false

test_script:
  - python runtests.py

after_test:
  - cmd: set PYTHONPATH=C:\projects\qwatson;%PYTHONPATH%
  - cd ./releases
  - pyinstaller.exe gwhat.spec
  - cd ..

on_success:
  - codecov
  
artifacts:
  - path: 'dist/*.zip'
  - path: 'dist/*.exe'

on_finish:
#   - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
