# https://ci.appveyor.com/project/jnsebgosselin/qwatson

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  matrix:
    - PYTHON_VERSION: "3.6"

platform:
  -x64

skip_branch_with_pr: true

install:
  # If there is a newer build queued for the same PR, cancel this one.
  # The AppVeyor 'rollout builds' option is supposed to serve the same
  # purpose but it is problematic because it tends to cancel builds pushed
  # directly to master instead of just PR builds (or the converse).
  # credits: JuliaLang developers.
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - cmd: set PATH=C:\Python36-x64;C:\Python36-x64\Scripts;%PATH%

  # Setup QWatson dev requirements.
  - python -m pip install -r requirements-dev.txt

  # Setup requirements for packaging QWatson.
  - python -m pip install pyinstaller
  - python -m pip install pywin32
  - python -m pip install tornado

build: false

test_script:
  - python setup.py build_ext --inplace
  - python runtests.py

on_success:
  - codecov

on_finish:
#   - ps: $blockRdp = $false; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
